package database;
// Generated Dec 18, 2019 4:06:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * BackendUserLog generated by hbm2java
 */
public class BackendUserLog  implements java.io.Serializable {


     private Integer id;
     private BackendUser backendUser;
     private Date dateTime;
     private String logstatus;

    public BackendUserLog() {
    }

    public BackendUserLog(BackendUser backendUser, Date dateTime, String logstatus) {
       this.backendUser = backendUser;
       this.dateTime = dateTime;
       this.logstatus = logstatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BackendUser getBackendUser() {
        return this.backendUser;
    }
    
    public void setBackendUser(BackendUser backendUser) {
        this.backendUser = backendUser;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getLogstatus() {
        return this.logstatus;
    }
    
    public void setLogstatus(String logstatus) {
        this.logstatus = logstatus;
    }




}


