package database;
// Generated Dec 18, 2019 4:06:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String cname;
     private String cdesc;
     private String cstatus;
     private Set<SpecifiedFeature> specifiedFeatures = new HashSet<SpecifiedFeature>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }

	
    public Category(String cname, String cstatus) {
        this.cname = cname;
        this.cstatus = cstatus;
    }
    public Category(String cname, String cdesc, String cstatus, Set<SpecifiedFeature> specifiedFeatures, Set<Product> products) {
       this.cname = cname;
       this.cdesc = cdesc;
       this.cstatus = cstatus;
       this.specifiedFeatures = specifiedFeatures;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public String getCdesc() {
        return this.cdesc;
    }
    
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc;
    }
    public String getCstatus() {
        return this.cstatus;
    }
    
    public void setCstatus(String cstatus) {
        this.cstatus = cstatus;
    }
    public Set<SpecifiedFeature> getSpecifiedFeatures() {
        return this.specifiedFeatures;
    }
    
    public void setSpecifiedFeatures(Set<SpecifiedFeature> specifiedFeatures) {
        this.specifiedFeatures = specifiedFeatures;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


