package database;
// Generated Dec 18, 2019 4:06:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Feature generated by hbm2java
 */
public class Feature  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String fstatus;
     private Set<SpecifiedFeature> specifiedFeatures = new HashSet<SpecifiedFeature>(0);
     private Set<ProductFeature> productFeatures = new HashSet<ProductFeature>(0);

    public Feature() {
    }

	
    public Feature(String fname, String fstatus) {
        this.fname = fname;
        this.fstatus = fstatus;
    }
    public Feature(String fname, String fstatus, Set<SpecifiedFeature> specifiedFeatures, Set<ProductFeature> productFeatures) {
       this.fname = fname;
       this.fstatus = fstatus;
       this.specifiedFeatures = specifiedFeatures;
       this.productFeatures = productFeatures;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getFstatus() {
        return this.fstatus;
    }
    
    public void setFstatus(String fstatus) {
        this.fstatus = fstatus;
    }
    public Set<SpecifiedFeature> getSpecifiedFeatures() {
        return this.specifiedFeatures;
    }
    
    public void setSpecifiedFeatures(Set<SpecifiedFeature> specifiedFeatures) {
        this.specifiedFeatures = specifiedFeatures;
    }
    public Set<ProductFeature> getProductFeatures() {
        return this.productFeatures;
    }
    
    public void setProductFeatures(Set<ProductFeature> productFeatures) {
        this.productFeatures = productFeatures;
    }




}


