package database;
// Generated Dec 18, 2019 4:06:31 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FrontUser generated by hbm2java
 */
public class FrontUser  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String password;
     private Date dateCreated;
     private Date dateUpdate;
     private String image;
     private String fuserStatus;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public FrontUser() {
    }

	
    public FrontUser(String name, String email, String password, Date dateCreated, String fuserStatus) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.dateCreated = dateCreated;
        this.fuserStatus = fuserStatus;
    }
    public FrontUser(String name, String email, String password, Date dateCreated, Date dateUpdate, String image, String fuserStatus, Set<Cart> carts, Set<Order> orders) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.dateCreated = dateCreated;
       this.dateUpdate = dateUpdate;
       this.image = image;
       this.fuserStatus = fuserStatus;
       this.carts = carts;
       this.orders = orders;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdate() {
        return this.dateUpdate;
    }
    
    public void setDateUpdate(Date dateUpdate) {
        this.dateUpdate = dateUpdate;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getFuserStatus() {
        return this.fuserStatus;
    }
    
    public void setFuserStatus(String fuserStatus) {
        this.fuserStatus = fuserStatus;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


