package database;
// Generated Dec 18, 2019 4:06:31 PM by Hibernate Tools 3.6.0



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private String filePath;

    public Image() {
    }

    public Image(Product product, String filePath) {
       this.product = product;
       this.filePath = filePath;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }




}


