package database;
// Generated Dec 18, 2019 4:06:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String id;
     private Category category;
     private String pname;
     private String pdesc;
     private String department;
     private double price;
     private int maxQtyOrderPerDay;
     private String psearchName;
     private String pstatus;
     private String warrantyDetails;
     private int mpsDateCount;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<OrderProduct> orderProducts = new HashSet<OrderProduct>(0);
     private Set<ProductFeature> productFeatures = new HashSet<ProductFeature>(0);
     private Set<Image> images = new HashSet<Image>(0);

    public Product() {
    }

	
    public Product(String id, Category category, String pname, String department, double price, int maxQtyOrderPerDay, String psearchName, String pstatus, int mpsDateCount) {
        this.id = id;
        this.category = category;
        this.pname = pname;
        this.department = department;
        this.price = price;
        this.maxQtyOrderPerDay = maxQtyOrderPerDay;
        this.psearchName = psearchName;
        this.pstatus = pstatus;
        this.mpsDateCount = mpsDateCount;
    }
    public Product(String id, Category category, String pname, String pdesc, String department, double price, int maxQtyOrderPerDay, String psearchName, String pstatus, String warrantyDetails, int mpsDateCount, Set<Cart> carts, Set<OrderProduct> orderProducts, Set<ProductFeature> productFeatures, Set<Image> images) {
       this.id = id;
       this.category = category;
       this.pname = pname;
       this.pdesc = pdesc;
       this.department = department;
       this.price = price;
       this.maxQtyOrderPerDay = maxQtyOrderPerDay;
       this.psearchName = psearchName;
       this.pstatus = pstatus;
       this.warrantyDetails = warrantyDetails;
       this.mpsDateCount = mpsDateCount;
       this.carts = carts;
       this.orderProducts = orderProducts;
       this.productFeatures = productFeatures;
       this.images = images;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public String getPdesc() {
        return this.pdesc;
    }
    
    public void setPdesc(String pdesc) {
        this.pdesc = pdesc;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getMaxQtyOrderPerDay() {
        return this.maxQtyOrderPerDay;
    }
    
    public void setMaxQtyOrderPerDay(int maxQtyOrderPerDay) {
        this.maxQtyOrderPerDay = maxQtyOrderPerDay;
    }
    public String getPsearchName() {
        return this.psearchName;
    }
    
    public void setPsearchName(String psearchName) {
        this.psearchName = psearchName;
    }
    public String getPstatus() {
        return this.pstatus;
    }
    
    public void setPstatus(String pstatus) {
        this.pstatus = pstatus;
    }
    public String getWarrantyDetails() {
        return this.warrantyDetails;
    }
    
    public void setWarrantyDetails(String warrantyDetails) {
        this.warrantyDetails = warrantyDetails;
    }
    public int getMpsDateCount() {
        return this.mpsDateCount;
    }
    
    public void setMpsDateCount(int mpsDateCount) {
        this.mpsDateCount = mpsDateCount;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<OrderProduct> getOrderProducts() {
        return this.orderProducts;
    }
    
    public void setOrderProducts(Set<OrderProduct> orderProducts) {
        this.orderProducts = orderProducts;
    }
    public Set<ProductFeature> getProductFeatures() {
        return this.productFeatures;
    }
    
    public void setProductFeatures(Set<ProductFeature> productFeatures) {
        this.productFeatures = productFeatures;
    }
    public Set<Image> getImages() {
        return this.images;
    }
    
    public void setImages(Set<Image> images) {
        this.images = images;
    }




}


