package database;
// Generated Dec 18, 2019 4:06:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer id;
     private String role;
     private String status;
     private Set<BackendUser> backendUsers = new HashSet<BackendUser>(0);

    public Role() {
    }

	
    public Role(String role, String status) {
        this.role = role;
        this.status = status;
    }
    public Role(String role, String status, Set<BackendUser> backendUsers) {
       this.role = role;
       this.status = status;
       this.backendUsers = backendUsers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<BackendUser> getBackendUsers() {
        return this.backendUsers;
    }
    
    public void setBackendUsers(Set<BackendUser> backendUsers) {
        this.backendUsers = backendUsers;
    }




}


