package database;
// Generated Dec 18, 2019 4:06:31 PM by Hibernate Tools 3.6.0



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer id;
     private String sname;
     private String saddress1;
     private String saddress2;
     private String sstreet;
     private String scity;
     private String scontactNo;
     private String email;
     private String sstatus;

    public Supplier() {
    }

	
    public Supplier(String sname, String saddress1, String scity, String scontactNo, String sstatus) {
        this.sname = sname;
        this.saddress1 = saddress1;
        this.scity = scity;
        this.scontactNo = scontactNo;
        this.sstatus = sstatus;
    }
    public Supplier(String sname, String saddress1, String saddress2, String sstreet, String scity, String scontactNo, String email, String sstatus) {
       this.sname = sname;
       this.saddress1 = saddress1;
       this.saddress2 = saddress2;
       this.sstreet = sstreet;
       this.scity = scity;
       this.scontactNo = scontactNo;
       this.email = email;
       this.sstatus = sstatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getSaddress1() {
        return this.saddress1;
    }
    
    public void setSaddress1(String saddress1) {
        this.saddress1 = saddress1;
    }
    public String getSaddress2() {
        return this.saddress2;
    }
    
    public void setSaddress2(String saddress2) {
        this.saddress2 = saddress2;
    }
    public String getSstreet() {
        return this.sstreet;
    }
    
    public void setSstreet(String sstreet) {
        this.sstreet = sstreet;
    }
    public String getScity() {
        return this.scity;
    }
    
    public void setScity(String scity) {
        this.scity = scity;
    }
    public String getScontactNo() {
        return this.scontactNo;
    }
    
    public void setScontactNo(String scontactNo) {
        this.scontactNo = scontactNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSstatus() {
        return this.sstatus;
    }
    
    public void setSstatus(String sstatus) {
        this.sstatus = sstatus;
    }




}


